workflows:

  android-build-workflow:

    name: Build Android APK

    labels:
      - QA
      # Remove the line with TENANT_NAME if not needed
      # - ${TENANT_NAME}

    instance_type: mac_mini_m2

    max_build_duration: 60

    inputs:
      tenant_name:
        description: The tenant name for this build
        default: Codemagic

    environment:
      vars:
        PUBLIC_ENV_VAR: "value here"
        # Define any necessary variables here, but don't include TENANT_NAME

    cache:
      cache_paths:
        - ~/.gradle/caches

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false

    scripts:
      - chmod +x gradlew
      - ./gradlew clean
      - ./gradlew assembleRelease
      - echo "Build completed"
      - ./gradlew assembleRelease --info  # Or use --debug for more detailed output

    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk

    publishing:
      email:
        recipients:
          - name@example.com

      scripts:
        - echo 'Post-publish script executed'
